// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://devjwcxxgopumyfbdnzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldmp3Y3h4Z29wdW15ZmJkbnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NjM0OTMsImV4cCI6MjA5NDQzOTQ5M30.GqAvGdPjT40UaQeiyfVCSlXDsXopNrutjMNz7v_h55E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});